import os
import subprocess
import tempfile
import uuid
import shutil

class SandboxExecutor:
    def __init__(self):
        self.base_dir = os.path.dirname(os.path.abspath(__file__))
        self.workspace_dir = os.path.join(self.base_dir, "workspace")
        os.makedirs(self.workspace_dir, exist_ok=True)
        
    def execute_python(self, code: str) -> dict:
        """
        Executes python code in an isolated workspace.
        Returns the stdout, stderr, and any newly generated files.
        """
        # Create a unique run folder to avoid conflicts
        run_id = str(uuid.uuid4())[:8]
        run_dir = os.path.join(self.workspace_dir, f"run_{run_id}")
        os.makedirs(run_dir, exist_ok=True)
        
        script_path = os.path.join(run_dir, "agent_script.py")
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(code)
            
        try:
            # Run the script with cwd set to the run_dir
            # This ensures any relative file writes stay in the run_dir
            process = subprocess.Popen(
                ["python", "agent_script.py"],
                cwd=run_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            stdout, stderr = process.communicate(timeout=30)
            
            # Find any files generated by the script (excluding the script itself)
            generated_files = []
            for file in os.listdir(run_dir):
                if file != "agent_script.py":
                    generated_files.append(os.path.join(run_dir, file))
                    
            return {
                "status": "success" if process.returncode == 0 else "error",
                "stdout": stdout,
                "stderr": stderr,
                "generated_files": generated_files,
                "run_dir": run_dir
            }
            
        except subprocess.TimeoutExpired:
            process.kill()
            return {
                "status": "error",
                "stdout": "",
                "stderr": "Timeout exceeded (30 seconds).",
                "generated_files": [],
                "run_dir": run_dir
            }
        except Exception as e:
            return {
                "status": "error",
                "stdout": "",
                "stderr": str(e),
                "generated_files": [],
                "run_dir": run_dir
            }

if __name__ == "__main__":
    executor = SandboxExecutor()
    code = """
import os
print("Hello from sandbox!")
with open("test.txt", "w") as f:
    f.write("This is a generated file.")
"""
    result = executor.execute_python(code)
    print("Result:", result)
