[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200


[dev]
  command = "npm run dev -- --port 5174"
  port = 5173
  targetPort = 5174
  framework = "vite"
